"""tasks status 改枚举

Revision ID: f6035c624d26
Revises: 8d974c782604
Create Date: 2026-09-12 10:44:35.297077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f6035c624d26'
down_revision: Union[str, Sequence[str], None] = '8d974c782604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=mysql.TEXT(),
               type_=sa.Enum('pending', 'running', 'done', 'failed', name='tasks_status'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('pending', 'running', 'done', 'failed', name='tasks_status'),
               type_=mysql.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
